### PR TITLE
Try to make a binary_search that is always producing the lower bound

### PR DESCRIPTION
**Pull request by bluss**
I didn't intend for this to be the final version, only the first working
version of a binary_search that always returns the lower bound. But it
seems to perform well (please test and see if it performs exactly as
well on your machine).

Any improvements on top of this are very interesting as well.

Code adapted from
http://en.cppreference.com/w/cpp/algorithm/lower_bound; the first
example, so not so much thinking went into it.

### CODE REVIEW

**Comment by alkis** [comment]
This is always slower. The reason is that the code inside the conditional is not one instruction either way so we end up with 2 cmoves per iteration. The runtime is similar to the one in the standard library today. See benchmarks:

```diff,ignored
 name        fast_binary_search:: ns/iter  fast_binary_search2:: ns/iter  diff ns/iter   diff %  speedup
-l1::dups    10                            35                                       25  250.00%   x 0.29
-l1::unique  10                            35                                       25  250.00%   x 0.29
-l2::dups    19                            55                                       36  189.47%   x 0.35
-l2::unique  19                            54                                       35  184.21%   x 0.35
-l3::dups    78                            131                                      53   67.95%   x 0.60
-l3::unique  80                            128                                      48   60.00%   x 0.62
```

**Comment by bluss** [comment]
Ah. Yeah, sorry, I looked at the wrong benchmark numbers! I wouldn't have submitted it if I didn't think it showed equal numbers as the other fast binary search.

**Comment by alkis** [comment]
No worries. It took me several iterations playing with this variant until I got convinced there is no way to salvage it :-)

**Comment by bluss** [comment]
Using the current lower_bound in the repo and making a binary search out of it, that would be possible, but does it always need two comparisons at the end?

**Comment by alkis** [comment]
Yes I tried that, I couldn't get it as fast as the current implementation. It was consistently 15ns for L1, high 20ies L2 and almost 100 L3.

**Comment by alkis** [comment]
Any more experiments we want to do here? Or should we move forward with current implementation and: https://github.com/rust-lang/rust/pull/45333

**Comment by bluss** [comment]
Sure, we should just get on with the PR. It does seem like a shame to not be able to guarantee the lower bound output, but it seems to be superior in other regards. And the usefulness of lower bound should mean that method appears in libcore sooner or later.

**Comment by alkis** [comment]
Sounds good to me. I am closing this PR.

**Pull request closed without merging**
